// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgV4G_eej_dGWbMyaaF-W9C8cINJjpusw',
    appId: '1:331812083332:web:2a99e73470b4c7d46154d1',
    messagingSenderId: '331812083332',
    projectId: 'jva-projecttracker',
    authDomain: 'jva-projecttracker.firebaseapp.com',
    storageBucket: 'jva-projecttracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAia23Zxmqm7vhh0N01qYytFuEEWp0OL14',
    appId: '1:331812083332:android:e9eac1ab5909c5936154d1',
    messagingSenderId: '331812083332',
    projectId: 'jva-projecttracker',
    storageBucket: 'jva-projecttracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfAIdYKuIuP7WKYNl-z_BQ8mkYHTWgDq4',
    appId: '1:331812083332:ios:569ed6f48d4603e86154d1',
    messagingSenderId: '331812083332',
    projectId: 'jva-projecttracker',
    storageBucket: 'jva-projecttracker.firebasestorage.app',
    iosBundleId: 'com.jva.jvaProjecttracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfAIdYKuIuP7WKYNl-z_BQ8mkYHTWgDq4',
    appId: '1:331812083332:ios:5bb903219c4cbd436154d1',
    messagingSenderId: '331812083332',
    projectId: 'jva-projecttracker',
    storageBucket: 'jva-projecttracker.firebasestorage.app',
    iosBundleId: 'com.jvalmacis.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgV4G_eej_dGWbMyaaF-W9C8cINJjpusw',
    appId: '1:331812083332:web:16a698db899a9f1c6154d1',
    messagingSenderId: '331812083332',
    projectId: 'jva-projecttracker',
    authDomain: 'jva-projecttracker.firebaseapp.com',
    storageBucket: 'jva-projecttracker.firebasestorage.app',
  );
}
